---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: retro-board
  name: retro-board-key-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: key-service
  namespace: retro-board
  labels:
    name: key-service
    app: key-service
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: key-service
  template:
    metadata:
      labels:
        app: key-service
        name: key-service
    spec:
      serviceAccountName: retro-board-key-service
      imagePullSecrets:
        - name: regcred
      containers:
        - name: key-service
          image: containers.chewedfeed.com/retro-board/key-service:latest
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
          ports:
            - containerPort: 3000
          env:
            - name: DEVELOPMENT
              value: "false"
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: backend-vault-token
                  key: token
            - name: MONGO_HOST
              valueFrom:
                secretKeyRef:
                  name: key-service-secrets
                  key: MONGO_HOST
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: key-service-secrets
                  key: MONGO_USER
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: key-service-secrets
                  key: MONGO_PASS
            - name: ONE_PASSWORD_PATH
              valueFrom:
                secretKeyRef:
                  name: key-service-secrets
                  key: ONE_PASSWORD_PATH
            - name: SERVICE_DEPENDENCIES
              valueFrom:
                secretKeyRef:
                  name: key-service-secrets
                  key: SERVICE_DEPENDENCIES
            - name: "SERVICE_NAME"
              value: "key-service"

---
apiVersion: v1
kind: Service
metadata:
  name: key-service
  namespace: retro-board
  labels:
    app: key-service
    name: key-service
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: key-service
