---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: retro-board
  name: retro-board-permission-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: permission-service
  namespace: retro-board
  labels:
    name: permission-service
    app: permission-service
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: permission-service
  template:
    metadata:
      labels:
        app: permission-service
        name: permission-service
    spec:
      serviceAccountName: retro-board-permission-service
      imagePullSecrets:
        - name: regcred
      containers:
        - name: permission-service
          image: containers.chewedfeed.com/retro-board/permission-service:latest
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
          ports:
            - containerPort: 3000
              name: http
            - containerPort: 8001
              name: grpc
          env:
            - name: DEVELOPMENT
              value: "false"
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: backend-vault-token
                  key: token
            - name: MONGO_HOST
              valueFrom:
                secretKeyRef:
                  name: permission-service-secrets
                  key: MONGO_HOST
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: permission-service-secrets
                  key: MONGO_USER
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: permission-service-secrets
                  key: MONGO_PASS
            - name: ONE_PASSWORD_PATH
              valueFrom:
                secretKeyRef:
                  name: permission-service-secrets
                  key: ONE_PASSWORD_PATH
            - name: SERVICE_NAME
              value: permission-service

---
apiVersion: v1
kind: Service
metadata:
  name: permission-service
  namespace: retro-board
  labels:
    app: permission-service
    name: permission-service
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
      name: http
    - port: 8001
      protocol: TCP
      targetPort: 8001
      name: grpc
  selector:
    app: permission-service
